<?php $this->setLayout('full'); ?>

<div class="row">
    <div class="col-md-7 col-center">

        <div class="light">
            <h1><?php echo Language::getText('activate_header'); ?></h1>

            <?php if ($message): ?>
                <div class="alert <?php echo convertAlertToBootstrap($messageType); ?>"><?php echo $message; ?></div>
            <?php endif; ?>
        </div>

    </div>
</div>
