<?php
$this->addMeta('videoCount', $videoCount);
$this->addMeta('playlistCount', $playlistCount);
$this->addMeta('thumbUrl', $config->thumbUrl);
if (!empty($watchLaterPlaylistId)) $this->addMeta('watchLaterPlaylistId', $watchLaterPlaylistId);
$this->setLayout('full');
?>

<div class="alert hidden"></div>

<h1><?=$member->username?></h1>

<!-- BEGIN Member Avatar/Profile Information -->
<div class="media">
    <div class="media-left">
        <?php $avatar = $this->getService('User')->getAvatarUrl($member); ?>
        <img class="media-object" src="<?=($avatar) ? $avatar : $this->options->themeUrl . '/images/avatar.gif'?>" alt="<?=$member->username?>" />
        <a class="btn btn-primary btn-sm subscribe" data-user="<?=$member->userId?>" data-type="<?=$subscribe_text?>" href=""><?=Language::GetText($subscribe_text)?></a>
    </div>
    <div class="media-body">
        <p>
            <a href="<?=HOST?>/account/message/send/<?=$member->username?>/" title="<?=Language::GetText('send_message')?>"><?=Language::GetText('send_message')?></a>&nbsp;&nbsp;&nbsp;
            <a class="flag" data-type="user" data-id="<?=$member->userId?>" href="" title="<?=Language::GetText('report_abuse')?>"><?=Language::GetText('report_abuse')?></a>&nbsp;&nbsp;&nbsp;
        </p>
        <p><strong><?=Language::GetText('joined')?>:</strong>&nbsp; <?=date('m/d/Y', strtotime($member->dateCreated))?></p>
        <p><strong><?=Language::GetText('profile_views')?>:</strong>&nbsp; <?=$member->views?></p>
        <p><strong><?=Language::GetText('subscribers')?>:</strong>&nbsp; <?php echo $sub_count[0]; ?></p>
        <?php if (!empty ($member->website)): ?>
            <p><strong><?=Language::GetText('website')?>:</strong>&nbsp; 
            <a href="<?=$member->website?>" target="_blank" rel="nofollow"><?=Functions::CutOff ($member->website, 40);?></a></p>
        <?php endif; ?>
        <p><?=nl2br($member->aboutMe)?></p>
    </div>
</div>
<!-- END Member Avatar/Profile Information -->


<ul class="nav nav-tabs">
    <li class="active"><a href="#member-videos" data-toggle="tab"><?=Language::GetText('videos')?></a></li>
    <li><a href="#member-playlists" data-toggle="tab"><?=Language::GetText('playlists')?></a></li>
</ul>

<!-- BEGIN Tab Panes -->
<div class="tab-content">

    <!-- BEGIN Member's Videos -->
    <div id="member-videos" class="tab-pane active">
        <h3><?=Language::GetText('videos')?></h3>
        <?php if ($videoCount > 0): ?>
            <div class="video-list">
                <?php $this->RepeatingBlock('video.phtml', $videoList) ?>
            </div>
            <?php if ($videoCount > 9): ?>
                <p class="text-center load-more"><a href="" data-user="<?=$member->userId?>" data-limit="9" class="btn btn-primary"><?=Language::GetText('load_more')?></a></p>
            <?php endif ?>
        <?php else: ?>
            <p><?=Language::GetText('no_member_videos')?></p>
        <?php endif; ?>
    </div>
    <!-- END Member's Videos -->

    <!-- BEGIN Member's Playlists -->
    <div id="member-playlists" class="tab-pane">
        <h3><?=Language::GetText('playlists')?></h3>
        <?php if ($playlistCount > 0): ?>
            
            <div class="playlist-list">
                <?php $playlistService = new PlaylistService(); ?>
                <?php foreach ($playlist_list as $playlist): ?>
                    <div class="playlist <?=(empty($playlist->entries)) ? 'playlist-empty' : ''?>">

                        <?php if (!empty($playlist->entries)): ?>

                            <a href="<?=$playlistService->getUrl($playlist)?>" title="<?=$playlist->name?>">
                                <img width="240" height="135" src="<?=getPlaylistThumbnail($playlist)?>" />
                                <span class="video-count"><?=count($playlist->entries)?><br><?=Language::GetText('videos')?></span>
                                <span class="watch-all"><span class="glyphicon glyphicon-play"></span>Watch All</span>
                            </a>
                            <p class="title"><a href="<?=$playlistService->getUrl($playlist)?>" title="<?=$playlist->name?>"><?=$playlist->name?></a></p> 

                        <?php else: ?>

                            <div class="thumb">
                                <img width="240" height="135" src="<?=$this->options->themeUrl?>/images/playlist_placeholder.png" />
                                <span class="video-count"><?=count($playlist->entries)?><br><?=Language::GetText('videos')?></span>
                            </div>
                            <p class="title"><?=$playlist->name?></p>

                        <?php endif; ?>

                    </div>
                <?php endforeach; ?>
            </div>
            
            <?php if ($playlistCount > 9): ?>
                <p class="load-more text-center"><a href="" data-user="<?=$member->userId?>" data-limit="9" class="btn btn-primary"><?=Language::GetText('load_more')?></a></p>
            <?php endif ?>

        <?php else: ?>
            <p><strong><?=Language::GetText('no_member_playlists')?></strong></p>
        <?php endif; ?>
    </div>
    <!-- END Member's Playlists -->

</div>
<!-- END Tab Panes -->

