<?php $this->setLayout('full'); ?>

<div class="row">
    <div class="col-md-5 col-center">

        <h1><?=Language::getText('register_header')?></h1>

        <?=Language::getText('register_text', array ('sitename' => $config->sitename))?>
        
        <?php if ($message): ?>
            <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
        <?php endif; ?>

        <div class="form">

            <form action="<?=HOST?>/register/" method="post">

                <div class="form-group <?=(isset ($errors['email'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('email')?>:</label>
                    <input name="email" type="text" class="form-control" value="<?=(isset($errors, $user->email)) ? $user->email : ''?>" />
                </div>

                <div class="form-group has-feedback <?=(isset ($errors['username'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('username')?>:</label>
                    <span class="glyphicon glyphicon-info-sign" title="<?=Language::getText('username_req')?>" data-toggle="tooltip"></span>
                    <input name="username" type="text" class="form-control" value="<?=(isset($errors, $user->username)) ? $user->username : ''?>" maxlength="30" />
                    <span class="glyphicon form-control-feedback"></span>
                    <p class="help-block"></p>
                </div>

                <div class="form-group <?=(isset ($errors['password']) || isset($errors['match'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('password')?>:</label>
                    <input name="password" type="password" class="form-control" value="<?=(isset($errors, $user->password)) ? $user->password : ''?>" />
                </div>

                <div class="form-group <?=(isset ($errors['password_confirm']) || isset($errors['match'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('confirm_password')?>:</label>
                    <input name="confirm" type="password" class="form-control" value="<?=(isset($errors, $user->password)) ? $user->password : ''?>" />
                </div>

                <input type="hidden" name="submitted" value="TRUE" />
                <input type="hidden" name="token" value="<?=$token?>" />
                <input class="btn btn-primary" type="submit" name="button" value="<?=Language::getText('register_button')?>" />
            </form>

        </div>

    </div>
</div>