<!DOCTYPE html>
<html lang="<?php echo Language::getLocale(); ?>">
<head>
<title><?php echo $meta->title; ?></title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="themeUrl" content="<?php echo $this->options->themeUrl; ?>" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baseUrl" content="<?php echo BASE_URL; ?>" />
<meta name="themeUrl" content="<?php echo $this->options->themeUrl; ?>" />
<?php $this->writeMeta(); ?>
<?php Plugin::triggerEvent('theme.head'); ?>
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->options->themeUrl; ?>/images/favicon.ico" />

<!-- Vendors -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/font-awesome.min.css" />

<!-- Theme -->
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/cumulusclips.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/main.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/pages.css" />
<link rel="stylesheet" type="text/css" href="<?php echo $this->options->themeUrl; ?>/css/responsive.css" />
<?php $this->writeCSS(); ?>

</head>
<body class="<?php echo $this->cssHooks(); ?>">
<?php Plugin::triggerEvent('theme.body'); ?>

<?php $this->block('header.phtml'); ?>

<!-- BEGIN Content -->
<div class="content">
    <div class="container">

        <div class="row">
            <div class="col-xs-12">
                <?php echo $this->body(); ?>
            </div>
        </div>

    </div>
</div>
<!-- END Content -->

<?php $this->block('footer.phtml'); ?>

<script type="text/javascript" src="<?php echo $this->options->themeUrl; ?>/js/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->options->themeUrl; ?>/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->options->themeUrl; ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?php echo $this->options->themeUrl; ?>/js/cumulusclips.js"></script>
<script type="text/javascript" src="<?php echo $this->options->themeUrl; ?>/js/general.js"></script>
<?php $this->writeJs(); ?>

</body>
</html>