<?php

$video = $model;
$videoService = $this->getService('Video');

?>

<div class="video video-large">
    <div class="thumbnail">
        <a href="<?=$videoService->getUrl($video)?>/" title="<?=$video->title?>">
            <span class="glyphicon glyphicon-play"></span>
            <img width="240" height="135" src="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg" />
        </a>
    </div>
    <div class="info">
        <span class="glyphicon glyphicon-user"></span><?=$video->username?>
        <span class="duration"><span class="glyphicon glyphicon-time"></span><?=$video->duration?></span>
    </div>
    <p><a class="video-title" href="<?=$videoService->getUrl($video)?>/" title="<?=$video->title?>"><?=$video->title?></a></p>
</div>