<?php $this->SetLayout ('account'); ?>

<div class="row">
    <div class="col">
        <h4><?=Language::GetText('account_header')?>, <?=$loggedInUser->username?></h4>
    </div>
</div>

<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-4 text-center">
    <?php $avatar = $this->getService('User')->getAvatarUrl($loggedInUser); ?>
        <?php if ($avatar) : ?>
          <img src="<?= $avatar; ?>" class="img-thumbnail my-3" alt="">
        <?php else : ?>
	<p class="text-center mt-3 py-4"><i class="fas fa-user fa-lg" style="font-size: 128px;"></i></p>
        <?php endif ; ?>
           <p class="text-center"><a class="btn btn-outline-primary" href="<?=HOST?>/account/profile/#update_avatar"><?=Language::GetText('edit_avatar')?></a></p>
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <p><span><?=Language::GetText('first_name')?></span> <?=empty($loggedInUser->firstName) ? '-' : $loggedInUser->firstName?></p>
        <p><span><?=Language::GetText('last_name')?></span> <?=empty($loggedInUser->lastName) ? '-' : $loggedInUser->lastName?></p>
        <p><span><?=Language::GetText('email')?></span> <?=$loggedInUser->email?></p>
        <p><span><?=Language::GetText('website')?></span> <?=empty($loggedInUser->website) ? '-' : $loggedInUser->website?></p>
        <p><span><?=Language::GetText('about_me')?></span> <?=empty($loggedInUser->aboutMe) ? '-' : $loggedInUser->aboutMe?></p>
        <p><a href="<?=HOST?>/account/profile/" title="<?=Language::GetText('update_profile')?>"><?=Language::GetText('update_profile')?></a></p>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-body">
      <p class="card-text"><strong><?=Language::GetText('joined')?>:</strong> <?=date('m/d/Y', strtotime($loggedInUser->dateCreated))?></p>
      <p class="card-text"><strong><?=Language::GetText('last_login')?>:</strong> <?=date('m/d/Y', strtotime($loggedInUser->lastLogin))?></p>
      <p class="card-text"><strong><?=Language::GetText('profile_views')?>:</strong> <?=$loggedInUser->views?></p>
      </div>
    </div>
  </div>
</div>
