<?php
$this->SetLayout('account');
?>

<div class="row mb-4">
  <div class="col header-secondary">
    <h2><?=Language::GetText('change_password_header')?></h2>
    <p><?=Language::GetText('change_password_text')?></p>
    <?php ( isset($message) ) ? showAlertMessage($message, $message_type) : ''; ?>
  </div>
</div>
<form action="<?=HOST?>/account/change-password/" method="post">
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <label class="<?=(isset($errors['password']) || isset($errors['match'])) ? 'is-invalid' : ''?>" for="password"><?=Language::GetText('new_password')?></label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
      </div>
      <div class="form-group">
        <label class="<?=(isset($errors['confirm_password']) || isset($errors['match'])) ? 'error' : ''?>" for="confirm_password"><?=Language::GetText('confirm_password')?></label>
        <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="<?=Language::GetText('confirm_password')?>">
      </div>
  <input type="hidden" name="submitted" value="TRUE">
  <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>">
  <button class="btn btn-primary" type="submit"><?=Language::GetText('change_password_button')?></button>
</form>
