<?php
$this->setLayout('account');
?>

<div class="row">
  <div class="col header-secondary">
    <h2><?= Language::getText('message_inbox_header') ?></h2>
    <?php (isset($message)) ? showAlertMessage($message, $message_type) : ''; ?>
  </div>
</div>

<?php if (count($messages) > 0) : ?>
<div class="row py-3">
<div class="col">
  
  <form action="<?= BASE_URL ?>/account/message/inbox/" method="post">
    <table class="table" id="inbox">
      <thead class="thead-dark">
        <tr>
          <th scope="col"><?= Language::GetText('purge') ?></td>
          <th scope="col"><?= Language::GetText('message_status') ?></td>
          <th scope="col" class="subject"><?= Language::GetText('subject') ?></td>
          <th scope="col"><?= Language::GetText('sender') ?></td>
          <th scope="col"><?= Language::GetText('date') ?></td>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($messages as $message) : ?>
          <tr class="<?= $message->status == 'read' ? 'text-muted font-italic' : 'table-primary' ?>">
            <td><input type="checkbox" name="delete[]" value="<?= $message->messageId ?>" /></td>
            <td><?= $message->status == 'read' ? Language::GetText('read') : Language::GetText('unread') ?></td>
            <td><a href="<?= BASE_URL ?>/account/message/read/<?= $message->messageId ?>/" title="<?= htmlspecialchars($message->subject) ?>"><?= htmlspecialchars($message->subject) ?></a></td>
            <td><?= $message->username ?></td>
            <td><?= date('m/d/Y', strtotime($message->dateCreated)) ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    <div class="row_btn text-right">
      <input type="hidden" name="submitted" value="TRUE" />
      <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
      <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#confirmDelete">
          <?php echo Language::getText('purge_button'); ?>
        </button>
    </div>

    <!-- Confirmation Modal -->
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteHeader" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title h5" id="confirmDeleteHeader">Warning: Permanently Deleting Messages</p>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete the selected messages?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger">Delete</button>
      </div>
    </div>
  </div>
</div>
  </form>
</div>

  <?= $pagination->Paginate() ?>

<?php else : ?>
  <div class="row">
    <div class="col">
      <p class="alert alert-info"><?= Language::GetText('no_messages') ?></strong>
    </div>
  </div>
<?php endif; ?>