<?php
$this->addJs($this->options->themeUrl . '/js/vendor/jquery.iframe-transport.js');
$this->addJs($this->options->themeUrl . '/js/vendor/jquery.fileupload.js');
$this->addJs('general.js');
$this->addJs('fileupload.js');
$this->setLayout('account');
?>

<div class="row">
  <div class="col header-secondary">
    <h2><?=Language::getText('upload_header')?></h2>
    <?php ( isset($message) ) ? showAlertMessage($message, $message_type) : ''; ?>
  </div>
</div>

<div class="row">
  <div class="col">
    <form action="<?=HOST?>/account/upload/info/" method="post" enctype="multipart/form-data">
      <!-- BEGIN Basic Information Tab -->
      <div class="row">
        <div class="col-md-6">
          <h4 class="text-white bg-secondary p-2" id="basic-information"><?php echo Language::getText('video_basic_tab_header'); ?></h4>

          <label for="title"><?=Language::getText('title')?></label>
          <input type="text" class="form-control <?=(isset ($Errors['title'])) ? ' is-invalid' : ''?>" name="title" id="title" placeholder="<?=Language::getText('title')?>" value="<?=(!empty($video->title)) ? $video->title : ''?>">

          <label class="<?=(isset($errors['description'])) ? 'error' : ''?>" for="description"><?=Language::getText('description')?></label>
          <textarea name="description" class="form-control" id="description" rows="3" cols="100"><?=(!empty($video->description)) ? $video->description : ''?></textarea>

          <label for="tags"><?=Language::getText('tags')?></label>
          <input type="text" class="form-control <?=(isset ($errors['tags'])) ? ' is-invalid' : ''?>" name="tags" id="tags" placeholder="i.e. a, comma, separated, list, of, tags" value="<?=(!empty($video->tags)) ? implode(', ', $video->tags) : ''?>">

          <label for="category"><?=Language::getText('category')?></label>
          <select class="custom-select <?=(isset ($errors['cat_id'])) ? ' is-invalid' : ''?>" id="category" name="cat_id">
            <?php foreach ($categoryList as $category): ?>
            <option<?=(!empty($video->categoryId) && $category->categoryId == $video->categoryId) ? ' selected="selected"' : ''?> value="<?=$category->categoryId?>"><?=$category->name?></option>
            <?php endforeach; ?>
          </select>

        <!-- END Basic Information -->
        <!-- BEGIN Settings -->
          <div id="advanced-settings" class="py-4">
            <h4 class="text-white bg-secondary p-2" id="advanced-settings"><?php echo Language::getText('video_advanced_tab_header'); ?></h4>

            <ul class="list-group">
              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="disable_embed" name="disable_embed" <?=(!empty($video->disableEmbed)) ? 'checked="checked"' : ''?>>
                  <label class="custom-control-label" for="disable_embed"><?=Language::getText('disable_embed')?></label> (<?=Language::getText('disable_embed_description')?>)
                </div>
              </li>

              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="gated" name="gated" <?=(!empty($video->gated)) ? 'checked="checked"' : ''?>>
                  <label class="custom-control-label" for="gated"><?=Language::getText('gated')?></label> (<?=Language::getText('gated_description')?>)
                </div>
              </li>

              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="private_video" data-block="private_url" name="private" <?=(!empty($video->private)) ? 'checked="checked"' : ''?> data-toggle="collapse" data-target="#showPrivateLink" aria-expanded="false" aria-controls="showPrivateLink">
                  <label class="custom-control-label" for="private_video"><?=Language::getText('private')?></label> (<?=Language::getText('private_description')?>)
                  <div id="showPrivateLink" class="collapse" aria-labelledby="private_video">
                    <label class="<?=(isset($errors['private_url'])) ? 'error' : ''?>"><?=Language::getText('private_url')?>:</label><br />
                    <input class="form-control" type="text" id="privateLink" value="<?=HOST?>/private/videos/<?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?>/" readonly>
                    <input type="hidden" id="private_url" name="private_url" value="<?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?>" />
                    <p class="text-right pt-2">
                      <button type="button" id="regenerate" class="btn btn-sm btn-outline-primary"><?=Language::getText('regenerate')?></button>
                      <button type="button" class="btn btn-sm btn-outline-secondary btn-clipboard" data-clipboard-target="#privateLink">Copy to Clipboard</button>
                    </p>
                  </div>
                </div>
              </li>
              <li class="list-group-item">
                <div class="custom-control custom-switch">
                  <input type="checkbox" class="custom-control-input" value="1" id="closeComments" name="closeComments" <?=(!empty($video->commentsClosed)) ? 'checked="checked"' : ''?>>
                  <label class="custom-control-label" for="closeComments"><?=Language::getText('closeComments')?></label> (<?=Language::getText('closeCommentsDescription')?>)
                </div>
              </li>
          </div>
          <!-- END Settings -->
        </div>
        <div class="form-group col-md-6">

          <!-- BEGIN Attachments Section -->
          <div id="video-attachments">
            <?php if ($config->allowVideoAttachments): ?>
            <h4 class="text-white bg-secondary p-2" id="video-attachments"><?php echo Language::getText('video_attachments_tab_header'); ?></h4>
            <ul class="attachments list-group">
              <?php $attachmentCount = 0; ?>
              <?php foreach ($newFiles as $newFile): ?>
              <li class="attachment list-group-item">
                <?php echo attachmentItem( array( "name" => $newFile['name'], "size" => $newFile['size'], "temp" => $newFile['temp']), $attachmentCount, true ); ?>
              </li>
              <?php $attachmentCount++; ?>
              <?php endforeach; ?>

              <?php foreach ($newAttachmentFileIds as $fileId): ?>
              <?php $file = \Functions::arrayColumnFilter($fileId, 'fileId', $userAttachments); ?>
              <li class="attachment list-group-item existing-file" id="existing-file-<?php echo $fileId; ?>">
                <?php echo attachmentItem( array( "name" => $file[0]->name, "size" => $file[0]->filesize, "file" => $file[0]->fileId), $attachmentCount, false ); ?>
              </li>
              <?php $attachmentCount++; ?>
              <?php endforeach; ?>
            </ul>
            <div class="attachment-form attachment-form-upload pt-3">

              <h5><?php echo Language::getText('upload_new_attachment_header'); ?></h5>

              <div class="custom-file">
                <input
                  class="uploader custom-file-input form-control" 
                  id="upload"
                  type="file"
                  name="attachment-upload"
                  data-url="<?php echo BASE_URL; ?>/ajax/upload/"
                  data-text="<?php echo Language::getText('browse_files_button'); ?>"
                  data-limit="<?php echo $config->fileSizeLimit; ?>"
                  data-type="library"
                  />
                  <label class="custom-file-label" for="upload">Choose file</label>
              </div>
            </div>
            <?php if (!empty($userAttachments)): ?>
            <div class="attachment-form-existing mt-3">
              <h5><?php echo Language::getText('select_existing_attachment_header'); ?></h5>
              <p><?php echo Language::getText('select_existing_attachment_help'); ?></p>
              <ul class="list-group">
                <?php foreach ($userAttachments as $file): ?>
                <li class="list-group-item"><?php echo $file->name; ?> (<?php echo \Functions::formatBytes($file->filesize, 0); ?>) <a
                    id="select-existing-file-<?php echo $file->fileId; ?>"
                    class="float-right btn btn-sm <?php echo in_array($file->fileId, $newAttachmentFileIds) ? 'btn-outline-danger' : 'btn-outline-primary'; ?>"
                    href=""
                    data-file="<?php echo $file->fileId; ?>"
                    data-size="<?php echo $file->filesize; ?>"
                    title="<?php echo $file->name; ?>"
                    ><?php echo in_array($file->fileId, $newAttachmentFileIds) ? 'Remove' : 'Add'; ?></a></li>
                <?php endforeach; ?>
              </ul>
</div>
            <?php endif; ?>
          </div>
        <?php endif; ?>
        <!-- END Attachment Section -->
        </div>
      </div>
      <input type="hidden" name="submitted" value="TRUE" />
      <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
      <button type="submit" class="btn btn-primary"><?=Language::getText('upload_video_button')?></button>
    </form>
  </div>
</div>



