<?php $this->setLayout('full'); ?>

<div class="row">
    <div class="col-md-7 col-center">

        <h1><?=Language::GetText('contact_header')?></h1>
        <p><?=Language::getText('contact_text')?></p>

        <?php if ($message): ?>
            <div class="alert <?=convertAlertToBootstrap($messageType)?>"><?=$message?></div>
        <?php endif; ?>

        <div class="form">
            <form action="<?=HOST?>/contact/" method="post">

                <div class="form-group <?=(!empty($errors['name'])) ? 'has-error' : ''?>">
                    <label for="name" class="control-label"><?=Language::getText('name')?>:</label>
                    <input type="text" name="name" class="form-control" value="<?=(!empty($errors) && !empty($name)) ? htmlspecialchars($name) : ''?>" />
                </div>

                <div class="form-group <?=(!empty($errors['email'])) ? 'has-error' : ''?>">
                    <label for="email" class="control-label"><?=Language::getText('email')?>:</label>
                    <input type="text" name="email" class="form-control" value="<?=(!empty($errors) && !empty($email)) ? $email : ''?>" />
                </div>

                <div class="form-group <?=(!empty($errors['feedback'])) ? 'has-error' : ''?>">
                    <label for="feedback" class="control-label"><?=Language::getText('message')?>:</label>
                    <textarea name="feedback" cols="40" rows="9" class="form-control"><?=(!empty($errors) && !empty($feedback)) ? htmlspecialchars($feedback) : ''?></textarea>
                </div>

                <input type="hidden" value="TRUE" name="submitted" />
                <input class="btn btn-primary" type="submit" name="button" value="<?=Language::getText('contact_button')?>" />
            </form>
        </div>
        
    </div>
</div>
