<?php $this->setLayout('full'); ?>

<div class="row">
    <div class="col-md-7 col-center">

        <h1><?php echo Language::GetText('contact_header'); ?></h1>
        <p><?php echo Language::getText('contact_text'); ?></p>

        <?php if ($message): ?>
            <div class="alert <?php echo convertAlertToBootstrap($messageType); ?>"><?php echo $message; ?></div>
        <?php endif; ?>

        <div class="form">
            <form action="<?php echo BASE_URL; ?>/contact/" method="post">

                <div class="form-group <?php echo (!empty($errors['name'])) ? 'has-error' : ''; ?>">
                    <label for="name" class="control-label"><?php echo Language::getText('name'); ?>:</label>
                    <input type="text" name="name" class="form-control" value="<?php echo (!empty($errors) && !empty($name)) ? htmlspecialchars($name) : ''; ?>" />
                </div>

                <div class="form-group <?php echo (!empty($errors['email'])) ? 'has-error' : ''; ?>">
                    <label for="email" class="control-label"><?php echo Language::getText('email'); ?>:</label>
                    <input type="text" name="email" class="form-control" value="<?php echo (!empty($errors) && !empty($email)) ? $email : ''; ?>" />
                </div>

                <div class="form-group <?php echo (!empty($errors['feedback'])) ? 'has-error' : ''; ?>">
                    <label for="feedback" class="control-label"><?php echo Language::getText('message'); ?>:</label>
                    <textarea name="feedback" cols="40" rows="9" class="form-control"><?php echo (!empty($errors) && !empty($feedback)) ? htmlspecialchars($feedback) : ''; ?></textarea>
                </div>

                <input type="hidden" value="TRUE" name="submitted" />
                <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
                <input class="btn btn-primary" type="submit" name="button" value="<?php echo Language::getText('contact_button'); ?>" />
            </form>
        </div>

    </div>
</div>
