<?php

$this->setLayout('full');

?>

<div class="row">
    <div class="form-container col-md-5 col-center">

        <div id="login-form" class="collapse <?php echo ($forgot_submit) ? '' : 'in'; ?>">

            <h1><?php echo Language::getText('login_header'); ?></h1>

            <?php if ($message && $login_submit): ?>
                <div class="alert <?php echo convertAlertToBootstrap($message_type); ?>"><?php echo $message; ?></div>
            <?php endif; ?>

            <div class="form">
                <form action="<?php echo BASE_URL; ?>/login/" method="post">

                    <div class="form-group <?php echo $login_submit && !$username ? 'has-error':''; ?>">
                        <label class="control-label"><?php echo Language::getText('username'); ?>:</label>
                        <input name="username" type="text" class="form-control" value="<?php echo ($login_submit && $username) ? $username : ''; ?>" />
                    </div>

                    <div class="form-group <?php echo ($login_submit && !$password) ? 'has-error' : ''; ?>">
                        <label class="control-label"><?php echo Language::getText('password'); ?>:</label>
                        <input type="password" class="form-control" name="password" value="" />
                    </div>

                    <input type="hidden" name="redirect" value="<?php echo urlencode($redirect); ?>" />
                    <input type="hidden" name="submitted_login" value="TRUE" />
                    <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
                    <input class="btn btn-primary" type="submit" name="button" value="<?php echo Language::getText('login_button'); ?>" />

                </form>
                <?php if ($config->enableRegistrations): ?>
                    <p><a href="<?php echo BASE_URL; ?>/register/"><?php echo Language::getText('no_account'); ?></a></p>
                <?php endif; ?>
                <p><a href="#forgot-form" data-toggle="toggle" data-parent=".collapse"><?php echo Language::getText('forgot_your_login'); ?></a></p>
            </div>
        </div>

        <div id="forgot-form" class="collapse <?php echo ($forgot_submit) ? 'in' : ''; ?>">

            <h2><?php echo Language::getText('forgot_header'); ?></h2>

            <?php if ($message && $forgot_submit): ?>
                <div class="alert <?php echo convertAlertToBootstrap($message_type); ?>"><?php echo $message; ?></div>
            <?php endif; ?>

            <div class="form">
                <form action="<?php echo BASE_URL; ?>/login/" method="post">

                    <p><?php echo Language::getText('forgot_text'); ?></p>

                    <div class="form-group <?php echo ($forgot_submit && $message_type == 'errors') ? 'has-error' : ''; ?>">
                        <label class="control-label"><?php echo Language::getText('email'); ?>:</label>
                        <input type="text" class="form-control" name="email" />
                    </div>

                    <input type="hidden" name="submitted_forgot" value="TRUE" />
                    <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
                    <input class="btn btn-primary" type="submit" name="button" value="<?php echo Language::getText('forgot_button'); ?>" />
                </form>
                <p><a href="#login-form" data-toggle="toggle" data-parent=".collapse"><?php echo Language::getText('cancel'); ?></a></p>
            </div>

        </div>

    </div>
</div>