<?php $this->setLayout('full'); ?>

<div class="row">
    <div class="col-md-5 col-center">

        <h1><?php echo Language::getText('register_header'); ?></h1>

        <?php echo Language::getText('register_text', array ('sitename' => $config->sitename)); ?>

        <?php if ($message): ?>
            <div class="alert <?php echo convertAlertToBootstrap($message_type); ?>"><?php echo $message; ?></div>
        <?php endif; ?>

        <div class="form">

            <form action="<?php echo BASE_URL; ?>/register/" method="post">

                <div class="form-group <?php echo (isset ($errors['email'])) ? 'has-error' : ''; ?>">
                    <label class="control-label"><?php echo Language::getText('email'); ?>:</label>
                    <input name="email" type="text" class="form-control" value="<?php echo (isset($errors, $user->email)) ? $user->email : ''; ?>" />
                </div>

                <div class="form-group has-feedback <?php echo (isset ($errors['username'])) ? 'has-error' : ''; ?>">
                    <label class="control-label"><?php echo Language::getText('username'); ?>:</label>
                    <span class="glyphicon glyphicon-info-sign" title="<?php echo Language::getText('username_req'); ?>" data-toggle="tooltip"></span>
                    <input name="username" type="text" class="form-control" value="<?php echo (isset($errors, $user->username)) ? $user->username : ''; ?>" maxlength="30" />
                    <span class="glyphicon form-control-feedback"></span>
                    <p class="help-block"></p>
                </div>

                <div class="form-group <?php echo (isset ($errors['password']) || isset($errors['match'])) ? 'has-error' : ''; ?>">
                    <label class="control-label"><?php echo Language::getText('password'); ?>:</label>
                    <input name="password" type="password" class="form-control" value="<?php echo (isset($errors, $user->password)) ? $user->password : ''; ?>" />
                </div>

                <div class="form-group <?php echo (isset ($errors['password_confirm']) || isset($errors['match'])) ? 'has-error' : ''; ?>">
                    <label class="control-label"><?php echo Language::getText('confirm_password'); ?>:</label>
                    <input name="confirm" type="password" class="form-control" value="<?php echo (isset($errors, $user->password)) ? $user->password : ''; ?>" />
                </div>

                <input type="hidden" name="submitted" value="TRUE" />
                <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
                <input class="btn btn-primary" type="submit" name="button" value="<?php echo Language::getText('register_button'); ?>" />
            </form>

        </div>

    </div>
</div>