

<!-- BEGIN Footer -->
<footer class="dark">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>
                    <a title="<?php echo Language::getText('nav_link_1'); ?>" href=""><?php echo Language::getText('nav_link_1'); ?></a> &bull;
                    <a title="<?php echo Language::getText('nav_link_2'); ?>" href=""><?php echo Language::getText('nav_link_2'); ?></a> &bull;
                    <a title="<?php echo Language::getText('contact'); ?>" href="<?php echo BASE_URL; ?>/contact/"><?php echo Language::getText('contact'); ?></a> &bull;
                    <a title="<?php echo Language::getText('nav_link_3'); ?>" href=""><?php echo Language::getText('nav_link_3'); ?></a>&bull;
                    <a title="<?php echo Language::getText('nav_link_4'); ?>" href=""><?php echo Language::getText('nav_link_4'); ?></a>
                </p>
                <p><?php echo Language::getText('copyright', array('YEAR' => date('Y'))); ?></p>
            </div>
            <div class="right col-xs-12 col-md-6 text-right">
            </div>
        </div>
    </div>
</footer>
<!-- END Footer -->

<div id="overlay"></div>