<?php

$video = $model;
$videoService = $this->getService('Video');

?>

<div class="video video-large">
    <div class="thumb">
        <a href="<?php echo $videoService->getUrl($video); ?>/" title="<?php echo $video->title; ?>">
            <span class="glyphicon glyphicon-play"></span>
            <img width="240" height="135" src="<?php echo $config->thumbUrl; ?>/<?php echo $video->filename; ?>.jpg" />
        </a>
    </div>
    <div class="info">
        <span class="glyphicon glyphicon-user"></span><?php echo $video->username; ?>
        <span class="duration"><span class="glyphicon glyphicon-time"></span><?php echo $video->duration; ?></span>
    </div>
    <p><a href="<?php echo $videoService->getUrl($video); ?>/" title="<?php echo $video->title; ?>"><?php echo $video->title; ?></a></p>
</div>