<?php $this->SetLayout ('account'); ?>

<h1><?=Language::GetText('account_header')?> - <?=$loggedInUser->username?></h1>

<div class="row">

    <div class="col-xs-4 col-sm-3">
        <?php $avatar = $this->getService('User')->getAvatarUrl($loggedInUser); ?>
        <div class="avatar"><img alt="<?=$loggedInUser->username?>" src="<?=($avatar) ? $avatar : $this->options->themeUrl . '/images/avatar.gif'?>" /></div>
        <a href="<?=HOST?>/account/profile/#update_avatar"><?=Language::GetText('edit_avatar')?></a>
        <p><strong><?=Language::GetText('joined')?>:</strong> <?=date('m/d/Y', strtotime($loggedInUser->dateCreated))?><br>
        <strong><?=Language::GetText('last_login')?>:</strong> <?=date('m/d/Y', strtotime($loggedInUser->lastLogin))?><br>
        <strong><?=Language::GetText('profile_views')?>:</strong> <?=$loggedInUser->views?></p>
    </div>

    <div class="col-xs-8 col-sm-9">
        <p><span><?=Language::GetText('first_name')?>:</span> <?=empty($loggedInUser->firstName) ? '-' : $loggedInUser->firstName?></p>
        <p><span><?=Language::GetText('last_name')?>:</span> <?=empty($loggedInUser->lastName) ? '-' : $loggedInUser->lastName?></p>
        <p><span><?=Language::GetText('email')?>:</span> <?=$loggedInUser->email?></p>
        <p><span><?=Language::GetText('website')?>:</span> <?=empty($loggedInUser->website) ? '-' : $loggedInUser->website?></p>
        <p><span><?=Language::GetText('about_me')?>:</span> <?=empty($loggedInUser->aboutMe) ? '-' : $loggedInUser->aboutMe?></p>
        <p><a href="<?=HOST?>/account/profile/" title="<?=Language::GetText('update_profile')?>"><?=Language::GetText('update_profile')?></a></p>
    </div>

</div>

