<?php $this->SetLayout('account'); ?>

<h1><?=Language::GetText('change_password_header')?></h1>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>

<div class="form">
    <p><?=Language::GetText('change_password_text')?></p>
    <form action="<?=HOST?>/account/change-password/" method="post">

        <div class="form-group <?=(isset($errors['password']) || isset($errors['match'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('new_password')?>:</label>
            <input class="form-control" type="password" name="password" />
        </div>
        <div class="form-group <?=(isset($errors['confirm_password']) || isset($errors['match'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('confirm_password')?>:</label>
            <input class="form-control" type="password" name="confirm_password" />
        </div>

        <input type="hidden" name="submitted" value="TRUE" />
        <input class="btn btn-primary" type="submit" name="button" value="<?=Language::GetText('change_password_button')?>" />
    </form>
</div>