<?php $this->SetLayout ('account'); ?>
<?php $playlistService = $this->getService('Playlist'); ?>

<h1><?=Language::GetText('playlists_edit_header')?>: <?=$playlistService->getPlaylistName($playlist)?></h1>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>

<p><a href="<?=HOST?>/account/playlists/"><?=Language::GetText('back_to_playlists')?></a></p>

<?php if ($playlist->type == 'playlist'): ?>

    <!-- BEGIN UPDATE PLAYLIST FORM -->
    <h2><?=Language::GetText('update_playlist_header')?></h2>

    <div class="form form-inline playlists-form">
        <form method="POST">
            <div class="form-group">
                <label><?=Language::GetText('playlist_name')?>:</label>
                <input class="form-control" type="text" name="name" value="<?=$playlist->name?>" />
            </div>

            <div class="form-group">
                <label><?=Language::GetText('visibility')?>:</label>
                <select class="form-control" name="visibility">
                    <option value="public" <?=($playlist->public) ? 'selected="selected"' : ''?>><?=Language::GetText('public')?></option>
                    <option value="private" <?=(!$playlist->public) ? 'selected="selected"' : ''?>><?=Language::GetText('private')?></option>
                </select>
            </div>
            <input type="hidden" name="submitted" value="true" />
            <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
            <input class="btn btn-primary" type="submit" value="<?=Language::GetText('update_playlist_button')?>" />
        </form>
    </div>
    <!-- END UPDATE PLAYLIST FORM -->

<?php endif; ?>


<h2><?=Language::GetText('playlist_videos')?></h2>
<?php if (count($playlist->entries) > 0): ?>

    <div class="video-list">
    <?php foreach ($videoList as $video): ?>
        <?php $videoService = $this->getService('Video'); ?>
        <div class="video video-large">
            <div class="thumbnail">
                <a href="<?=VideoService::getUrl($video)?>/?playlist=<?=$playlist->playlistId?>" title="<?=$video->title?>">
                    <span class="glyphicon glyphicon-play"></span>
                    <img width="240" height="135" src="<?=$config->thumbUrl?>/<?=$video->filename?>.jpg" />
                </a>
            </div>

            <div class="info">
                <span class="glyphicon glyphicon-user"></span><?=$video->username?>
                <span class="duration"><span class="glyphicon glyphicon-time"></span><?=$video->duration?></span>
            </div>

            <p><a href="<?=VideoService::getUrl($video)?>/?playlist=<?=$playlist->playlistId?>" title="<?=$video->title?>"><?=$video->title?></a></p>

            <div class="actions small">
                <a
                    class="text-danger"
                    data-toggle="confirm-modal"
                    data-text="<?php echo Language::getText('confirm_remove_playlist_video'); ?>"
                    href="<?php echo BASE_URL; ?>/account/playlists/edit/<?=$playlist->playlistId?>/?remove=<?=$video->videoId?>"
                    title="<?=Language::GetText('remove_playlist_video')?>"
                ><?=Language::GetText('remove_playlist_video')?></a>
            </div>
        </div>
    <?php endforeach; ?>
    </div>

<?php else: ?>
    <p><?=Language::GetText('no_videos_playlist')?></p>
<?php endif; ?>