<?php
$message_type = isset($message_type) ? $message_type : null;
$messageClass = $message_type ? '' : 'hidden';
$this->addJs('fileupload.jquery-ui.widget.js');
$this->addJs('fileupload.iframe-transport.js');
$this->addJs('fileupload.plugin.js');
$this->addJs('fileupload.js');
$this->SetLayout('account');
?>

<!--[if IE 9 ]> <meta name="ie9" content="true" /> <![endif]-->

<h1><?=Language::GetText('profile_header')?></h1>

<div class="alert <?=$messageClass?> <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>

<div class="form">

    <p><?=Language::GetText('asterisk')?></p>

    <form action="<?=HOST?>/account/profile/" method="post">

        <div class="form-group <?=(isset($Errors['first_name'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('first_name')?>:</label>
            <input class="form-control" type="text" name="first_name" value="<?=htmlspecialchars($loggedInUser->firstName)?>" />
        </div>

        <div class="form-group <?=(isset($Errors['last_name'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('last_name')?>:</label>
            <input class="form-control" type="text" name="last_name" value="<?=htmlspecialchars($loggedInUser->lastName)?>" />
        </div>

        <div class="form-group <?=(isset($Errors['email'])) ? 'has-error' : ''?>">
            <label class="control-label">*<?=Language::GetText('email')?>:</label>
            <input class="form-control" type="text" name="email" value="<?=htmlspecialchars($loggedInUser->email)?>" />
        </div>

        <div class="form-group <?=(isset($Errors['website'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('website')?>:</label>
            <input class="form-control" type="text" name="website" value="<?=htmlspecialchars($loggedInUser->website)?>" />
        </div>

        <div class="form-group <?=(isset($Errors['about_me'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::GetText('about_me')?>:</label>
            <textarea class="form-control" name="about_me" rows="10" cols="45"><?=htmlspecialchars($loggedInUser->aboutMe)?></textarea>
        </div>

        <input type="hidden" value="yes" name="submitted" />
        <input class="btn btn-primary" type="submit" name="button" value="<?=Language::GetText('profile_button')?>" />
    </form>
</div>

<h1><?=Language::GetText('update_avatar_header')?></h1>
<div id="update_avatar" class="form">
    <div class="row">

        <div class="col-xs-12 col-md-2">
            <?php $avatar = $this->getService('User')->getAvatarUrl($loggedInUser); ?>
            <p class="avatar"><span><img alt="<?=Language::GetText('current_avatar')?>" src="<?=($avatar) ? $avatar : $this->options->themeUrl . '/images/avatar.gif'?>"></span></p>
            <?=Language::GetText('current_avatar')?><br />
            <a class="confirm" data-node="confirm_reset_avatar" href="<?=HOST?>/account/profile/reset/"><?=Language::GetText('reset_avatar')?></a>
        </div>

        <div class="col-xs-12 col-md-10">
            <?=Language::GetText('update_avatar_text')?>
            <form name="upload" action="<?=HOST?>/account/upload/avatar/">
                <div id="upload-select-file" class="btn btn-primary">
                    <span><?=Language::getText('browse_files_button')?></span>
                    <input id="upload" type="file" name="upload" />
                </div>
                <input id="upload_button" class="btn btn-primary" type="button" value="<?=Language::GetText('update_avatar_button')?>" />
                <input type="hidden" name="timestamp" value="<?=$timestamp?>" />
                <input type="hidden" name="upload-limit" id="upload-limit" value="<?=1024*30?>" />
                <input type="hidden" name="file-types" id="file-types" value="<?=htmlspecialchars(json_encode($config->acceptedAvatarFormats))?>" />
                <input type="hidden" name="upload-type" id="upload-type" value="avatar" />


                <div id="upload_status" class="">
                    <div class="title"></div>
                    <div class="progress">
                        <div class="progress-bar"></div>
                    </div>
                    <a href="" title="<?=Language::GetText('cancel')?>"><?=Language::GetText('cancel')?></a>
                </div>

            </form>
        </div>

    </div>
</div>