<?php $this->setLayout('account'); ?>

<h1><?=Language::getText('upload_header')?></h1>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>

<div class="form">
    <form action="<?=HOST?>/account/upload/" method="post">

        <div class="form-group <?=(isset($errors['title'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('title')?>:</label>
            <input class="form-control" type="text" name="title" value="<?=(!empty($video->title)) ? $video->title : ''?>" />
        </div>

        <div class="form-group <?=(isset($errors['tags'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('tags')?>:</label>
            <input class="form-control" type="text" name="tags" value="<?=(!empty($video->tags)) ? implode(', ', $video->tags) : ''?>" />
            <p class="help-block"><?=Language::getText('comma_delimited')?></p>
        </div>

        <div class="form-group <?=(isset($errors['cat_id'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('category')?>:</label>
            <select class="form-control" name="cat_id">
            <?php foreach ($categoryList as $category): ?>
                <option<?=(!empty($video->categoryId) && $category->categoryId == $video->categoryId) ? ' selected="selected"' : ''?> value="<?=$category->categoryId?>"><?=$category->name?></option>
            <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group <?=(isset($errors['description'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('description')?>:</label>
            <textarea class="form-control" name="description" rows="10" cols="45"><?=(!empty($video->description)) ? $video->description : ''?></textarea>
        </div>

        <div class="form-group">
            <input id="disable_embed" type="checkbox" name="disable_embed" value="1" <?=(!empty($video->disableEmbed)) ? 'checked="checked"' : ''?> />
            <label for="disable_embed"><?=Language::getText('disable_embed')?></label> <em>(<?=Language::getText('disable_embed_description')?>)</em><br>
        </div>

        <div class="form-group">
            <label>
                <input id="gated_video" type="checkbox" name="gated" value="1" <?=(!empty($video->gated)) ? 'checked="checked"' : ''?> />
                <?=Language::getText('gated')?>
                <em>(<?=Language::getText('gated_description')?>)</em><br>
            </label>
        </div>

        <div class="form-group <?=(isset($errors['private_url'])) ? 'has-error' : ''?>">
            <label>
                <input id="private_video" data-toggle="collapse" data-target="#private-url" type="checkbox" name="private" value="1" <?=(!empty($video->private)) ? 'checked="checked"' : ''?> />
                <?=Language::getText('private')?>
                <em>(<?=Language::getText('private_description')?>)</em><br>
            </label>
                
            <p id="private-url" class="collapse <?=(!empty($video->private)) ? 'in' : ''?>">
                <label class="control-label">
                    <?=Language::getText('private_url')?>:
                    <?=HOST?>/private/videos/<span><?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?></span>/
                </label>

                <input type="hidden" name="private_url" value="<?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?>" />
                <a href="" class="small"><?=Language::getText('regenerate')?></a>
            </p>
        </div>

        <div class="form-group">
            <label>
                <input id="closeComments" type="checkbox" name="closeComments" value="1" <?=(!empty($video->commentsClosed)) ? 'checked="checked"' : ''?> />
                <?=Language::getText('closeComments')?>
                <em>(<?=Language::getText('closeCommentsDescription')?>)</em>
            </label>
        </div>

        <input type="hidden" name="submitted" value="TRUE" />
        <input class="btn btn-primary" type="submit" name="button" value="<?=Language::getText('submit_button')?>" />
    </form>
</div>