<?php

$this->addJs('fileupload.jquery-ui.widget.js');
$this->addJs('fileupload.iframe-transport.js');
$this->addJs('fileupload.plugin.js');
$this->addJs('fileupload.js');
$this->setLayout('account');

?>

<h1><?=Language::getText('upload_header')?></h1>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>


<ul class="nav nav-tabs">
    <li class="active"><a href="#basic-information" data-toggle="tab"><?php echo Language::getText('video_basic_tab'); ?></a></li>
    <?php if ($config->allowVideoAttachments): ?>
        <li><a href="#video-attachments" data-toggle="tab"><?php echo Language::getText('video_attachments_tab'); ?></a></li>
    <?php endif; ?>
    <li><a href="#advanced-settings" data-toggle="tab"><?php echo Language::getText('video_advanced_tab'); ?></a></li>
</ul>



<form action="<?=HOST?>/account/upload/info/" method="post">

    <!-- BEGIN Tab Panes -->
    <div class="tab-content video-information-form">

        <!-- BEGIN Basic Information Tab -->
        <div id="basic-information" class="tab-pane active">

            <h2><?php echo Language::getText('video_basic_tab_header'); ?></h2>

            <div class="form">

                <div class="form-group <?=(isset($errors['title'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('title')?>:</label>
                    <input class="form-control" type="text" name="title" value="<?=(!empty($video->title)) ? $video->title : ''?>" />
                </div>

                <div class="form-group <?=(isset($errors['tags'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('tags')?>:</label>
                    <input class="form-control" type="text" name="tags" value="<?=(!empty($video->tags)) ? implode(', ', $video->tags) : ''?>" />
                    <p class="help-block"><?=Language::getText('comma_delimited')?></p>
                </div>

                <div class="form-group <?=(isset($errors['cat_id'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('category')?>:</label>
                    <select class="form-control" name="cat_id">
                    <?php foreach ($categoryList as  $category): ?>
                        <option<?=(!empty($video->categoryId) && $category->categoryId == $video->categoryId) ? ' selected="selected"' : ''?> value="<?=$category->categoryId?>"><?=$category->name?></option>
                    <?php endforeach; ?>
                    </select>
                </div>

                <div class="form-group <?=(isset($errors['description'])) ? 'has-error' : ''?>">
                    <label class="control-label"><?=Language::getText('description')?>:</label>
                    <textarea class="form-control" name="description" rows="10" cols="45"><?=(!empty($video->description)) ? $video->description : ''?></textarea>
                </div>

            </div>

        </div>
        <!-- END Basic Information Tab -->


        <?php if ($config->allowVideoAttachments): ?>

            <!-- BEGIN Video Attachments Tab -->
            <div id="video-attachments" class="tab-pane">

                <h2><?php echo Language::getText('video_attachments_tab_header'); ?></h2>

                <div class="form">

                    <div class="attachments">

                        <?php $attachmentCount = 0; ?>
                        <?php foreach ($newFiles as $newFile): ?>

                            <div class="attachment">
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][name]" value="<?php echo $newFile['name']; ?>" />
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][size]" value="<?php echo $newFile['size']; ?>" />
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][temp]" value="<?php echo $newFile['temp']; ?>" />

                                <div class="upload-progress">
                                    <a class="remove" href=""><span class="glyphicon glyphicon-remove"></span></a>
                                    <span class="title"><?php echo $newFile['name']; ?> (<?php echo \Functions::formatBytes($newFile['size'],0); ?>)</span>
                                    <span class="pull-right glyphicon glyphicon-ok"></span>
                                </div>
                            </div>
                            <?php $attachmentCount++; ?>

                        <?php endforeach; ?>

                        <?php foreach ($newAttachmentFileIds as $fileId): ?>

                            <?php $file = \Functions::arrayColumnFilter($fileId, 'fileId', $userAttachments); ?>

                            <div class="attachment existing-file" id="existing-file-<?php echo $fileId; ?>">
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][name]" value="<?php echo $file[0]->name; ?>" />
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][size]" value="<?php echo $file[0]->filesize; ?>" />
                                <input type="hidden" name="attachment[<?php echo $attachmentCount; ?>][file]" value="<?php echo $file[0]->fileId; ?>" />

                                <div class="upload-progress">
                                    <a class="remove" href=""><span class="glyphicon glyphicon-remove"></span></a>
                                    <span class="title"><?php echo $file[0]->name; ?> (<?php echo \Functions::formatBytes($file[0]->filesize,0); ?>)</span>
                                    <span class="pull-right glyphicon glyphicon-ok"></span>
                                </div>
                            </div>
                            <?php $attachmentCount++; ?>

                        <?php endforeach; ?>

                    </div>

                    <div class="add">
                        <p><a href="" class="new">
                            <i class="glyphicon glyphicon-plus"></i> <?php echo Language::getText('upload_new_attachment'); ?>
                        </a></p>

                        <?php if (!empty($userAttachments)): ?>
                            <p><a href="" class="existing">
                                <i class="glyphicon glyphicon-plus"></i> <?php echo Language::getText('select_existing_attachment'); ?>
                            </a></p>
                        <?php endif; ?>
                    </div>

                    <div class="attachment-form attachment-form-upload hidden">

                        <div class="header">
                            <h3><?php echo Language::getText('upload_new_attachment_header'); ?></h3>
                            &bull; <a href="" class="cancel"><?php echo Language::getText('cancel'); ?></a>
                        </div>

                        <input
                            class="uploader"
                            type="file"
                            name="attachment-upload"
                            data-url="<?php echo BASE_URL; ?>/ajax/upload/"
                            data-text="<?php echo Language::getText('browse_files_button'); ?>"
                            data-limit="<?php echo $config->fileSizeLimit; ?>"
                            data-type="library"
                        />
                    </div>

                    <?php if (!empty($userAttachments)): ?>

                        <div class="attachment-form attachment-form-existing hidden">

                            <div class="header">
                                <h3><?php echo Language::getText('select_existing_attachment_header'); ?></h3>
                                &bull; <a href="" class="cancel"><?php echo Language::getText('cancel'); ?></a>
                            </div>

                            <p><?php echo Language::getText('select_existing_attachment_help'); ?></p>

                            <div class="list-group">
                                <?php foreach ($userAttachments as $file): ?>
                                    <a
                                        id="select-existing-file-<?php echo $file->fileId; ?>"
                                        class="<?php echo in_array($file->fileId, $newAttachmentFileIds) ? 'selected' : ''; ?> list-group-item"
                                        href=""
                                        data-file="<?php echo $file->fileId; ?>"
                                        data-size="<?php echo $file->filesize; ?>"
                                        title="<?php echo $file->name; ?>"
                                    ><?php echo $file->name; ?> <span><?php echo \Functions::formatBytes($file->filesize, 0); ?></span></a>
                                <?php endforeach; ?>
                            </div>
                        </div>

                    <?php endif; ?>

                </div>

            </div>
            <!-- END Video Attachments Tab -->

        <?php endif; ?>


        <!-- BEGIN Advacned Settings Tab -->
        <div id="advanced-settings" class="tab-pane">

            <h2><?php echo Language::getText('video_advanced_tab_header'); ?></h2>

            <div class="form">

                <div class="form-group">
                    <label>
                        <input type="checkbox" name="disable_embed" value="1" <?=($video->disableEmbed) ? 'checked="checked"' : ''?> />
                        <?=Language::getText('disable_embed')?>
                        <em>(<?=Language::getText('disable_embed_description')?>)</em>
                    </label>
                </div>

                <div class="form-group">
                    <label>
                        <input type="checkbox" name="gated" value="1" <?=($video->gated == '1') ? 'checked="checked"' : ''?> />
                        <?=Language::getText('gated')?>
                        <em>(<?=Language::getText('gated_description')?>)</em>
                    </label>
                </div>

                <div class="form-group <?=(isset($errors['private_url'])) ? 'has-error' : ''?>">
                    <label class="control-label">
                        <input data-target="#private-url" data-toggle="collapse" type="checkbox" name="private" value="1" <?=($video->private) ? 'checked="checked"' : ''?> />
                        <?=Language::getText('private')?>
                        <em>(<?=Language::getText('private_description')?>)</em><br>
                    </label>

                    <p id="private-url" class="collapse <?=($video->private) ? 'in' : ''?>">
                        <label class="control-label">
                            <?=Language::getText('private_url')?>:
                            <?=HOST?>/private/videos/<span><?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?></span>/
                        </label>

                        <input type="hidden" name="private_url" value="<?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?>" />
                        <a href="" class="small"><?=Language::getText('regenerate')?></a>
                    </p>
                </div>

                <div class="form-group">
                    <label>
                        <input type="checkbox" name="closeComments" value="1" <?=($video->commentsClosed == '1') ? 'checked="checked"' : ''?> />
                        <?=Language::getText('closeComments')?>
                        <em>(<?=Language::getText('closeCommentsDescription')?>)</em>
                    </label>
                </div>

            </div>

        </div>
        <!-- END Advacned Settings Tab -->

    </div>
    <!-- END Tab Panes -->

    <input type="hidden" name="submitted" value="TRUE" />
    <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
    <input class="btn btn-primary" type="submit" name="button" value="<?=Language::getText('update_video_button')?>" />

</form>
