<?php $this->setLayout('account'); ?>

<h1><?=Language::getText('update_video_header')?></h1>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>

<p><a href="<?=HOST?>/account/videos/"><?=Language::getText('back_to_videos')?></a></p>

<div class="form">

    <form action="<?=HOST?>/account/videos/edit/<?=$video->videoId?>/" method="post">

        <div class="form-group <?=(isset($errors['title'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('title')?>:</label>
            <input class="form-control" type="text" name="title" value="<?=$video->title?>" />
        </div>

        <div class="form-group <?=(isset($errors['tags'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('tags')?>:</label>
            <input class="form-control" type="text" name="tags" value="<?=implode(', ', $video->tags)?>" />
            <p class="help-block"><?=Language::getText('comma_delimited')?></p>
        </div>

        <div class="form-group <?=(isset($errors['cat_id'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('category')?>:</label>
            <select class="form-control" name="cat_id">
            <?php foreach ($categoryList as  $category): ?>
                <option value="<?=$category->categoryId?>"<?=($video->categoryId == $category->categoryId) ? ' selected="selected"' : ''?>><?=$category->name?></option>
            <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group <?=(isset($errors['description'])) ? 'has-error' : ''?>">
            <label class="control-label"><?=Language::getText('description')?>:</label>
            <textarea class="form-control" name="description" rows="10" cols="45"><?=$video->description?></textarea>
        </div>

        <div class="form-group">
            <label>
                <input type="checkbox" name="disable_embed" value="1" <?=($video->disableEmbed) ? 'checked="checked"' : ''?> />
                <?=Language::getText('disable_embed')?>
                <em>(<?=Language::getText('disable_embed_description')?>)</em>
            </label>
        </div>

        <div class="form-group">
            <label>
                <input type="checkbox" name="gated" value="1" <?=($video->gated == '1') ? 'checked="checked"' : ''?> />
                <?=Language::getText('gated')?>
                <em>(<?=Language::getText('gated_description')?>)</em>
            </label>
        </div>

        <div class="form-group <?=(isset($errors['private_url'])) ? 'has-error' : ''?>">
            <label class="control-label">
                <input data-target="#private-url" data-toggle="collapse" type="checkbox" name="private" value="1" <?=($video->private) ? 'checked="checked"' : ''?> />
                <?=Language::getText('private')?>
                <em>(<?=Language::getText('private_description')?>)</em><br>
            </label>

            <p id="private-url" class="collapse <?=($video->private) ? 'in' : ''?>">
                <label class="control-label">
                    <?=Language::getText('private_url')?>:
                    <?=HOST?>/private/videos/<span><?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?></span>/
                </label>

                <input type="hidden" name="private_url" value="<?=(!empty($video->privateUrl)) ? $video->privateUrl : $privateUrl?>" />
                <a href="" class="small"><?=Language::getText('regenerate')?></a>
            </p>
        </div>
        
        <div class="form-group">
            <label>
                <input type="checkbox" name="closeComments" value="1" <?=($video->commentsClosed == '1') ? 'checked="checked"' : ''?> />
                <?=Language::getText('closeComments')?>
                <em>(<?=Language::getText('closeCommentsDescription')?>)</em>
            </label>
        </div>

        <input type="hidden" name="submitted" value="TRUE" />
        <input class="btn btn-primary" type="submit" name="button" value="<?=Language::getText('update_video_button')?>" />
    </form>

</div>