<?php $this->SetLayout ('account'); ?>

<h1><?php echo Language::GetText('account_header'); ?> - <?php echo $loggedInUser->username; ?></h1>

<div class="row">

    <div class="col-xs-4 col-sm-3">
        <?php $avatar = $this->getService('User')->getAvatarUrl($loggedInUser); ?>
        <div class="avatar"><img alt="<?php echo $loggedInUser->username; ?>" src="<?php echo ($avatar) ? $avatar : $this->options->themeUrl . '/images/avatar.png'; ?>" /></div>
        <a href="<?php echo BASE_URL; ?>/account/profile/#update_avatar"><?php echo Language::GetText('edit_avatar'); ?></a>
        <p><strong><?php echo Language::GetText('joined'); ?>:</strong> <?php echo date('m/d/Y', strtotime($loggedInUser->dateCreated)); ?><br>
        <strong><?php echo Language::GetText('last_login'); ?>:</strong> <?php echo date('m/d/Y', strtotime($loggedInUser->lastLogin)); ?><br>
        <strong><?php echo Language::GetText('profile_views'); ?>:</strong> <?php echo $loggedInUser->views; ?></p>
    </div>

    <div class="col-xs-8 col-sm-9">
        <p><span><?php echo Language::GetText('first_name'); ?>:</span> <?php echo empty($loggedInUser->firstName) ? '-' : $loggedInUser->firstName; ?></p>
        <p><span><?php echo Language::GetText('last_name'); ?>:</span> <?php echo empty($loggedInUser->lastName) ? '-' : $loggedInUser->lastName; ?></p>
        <p><span><?php echo Language::GetText('email'); ?>:</span> <?php echo $loggedInUser->email; ?></p>
        <p><span><?php echo Language::GetText('website'); ?>:</span> <?php echo empty($loggedInUser->website) ? '-' : $loggedInUser->website; ?></p>
        <p><span><?php echo Language::GetText('about_me'); ?>:</span> <?php echo empty($loggedInUser->aboutMe) ? '-' : $loggedInUser->aboutMe; ?></p>
        <p><a href="<?php echo BASE_URL; ?>/account/profile/" title="<?php echo Language::GetText('update_profile'); ?>"><?php echo Language::GetText('update_profile'); ?></a></p>
    </div>

</div>

