<?php $this->SetLayout ('account'); ?>

<h1><?php echo Language::GetText('privacy_settings_header'); ?></h1>

<?php if ($message): ?>
    <div class="alert <?php echo convertAlertToBootstrap($message_type); ?>"><?php echo $message; ?></div>
<?php endif; ?>

<div class="form">
    <form action="<?php echo BASE_URL; ?>/account/privacy-settings/" method="post">


        <div class="form-group">
            <label><?php echo Language::GetText('alert_comment_reply'); ?>:</label>
            <select class="form-control" name="commentReply">
                <option value="1"<?php echo ($privacy->commentReply) ? ' selected="selected"' : ''; ?>><?php echo Language::GetText('yes'); ?></option>
                <option value="0"<?php echo (!$privacy->commentReply) ? ' selected="selected"' : ''; ?>><?php echo Language::GetText('no'); ?></option>
            </select>
        </div>

        <input type="hidden" name="video_ready" value="<?php echo (int) $privacy->videoReady; ?>" />
        <input type="hidden" name="video_comment" value="<?php echo (int) $privacy->videoComment; ?>" />
        <input type="hidden" name="new_video" value="<?php echo (int) $privacy->newVideo; ?>" />
        <input type="hidden" name="new_message" value="<?php echo (int) $privacy->newMessage; ?>" />
        <input type="hidden" name="submitted" value="TRUE" />
        <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
        <input class="btn btn-primary" type="submit" name="button" value="<?php echo Language::GetText('privacy_settings_button'); ?>" />
    </form>
</div>