<?php $this->SetLayout('account'); ?>


<?php if ($message): ?>
    <div class="alert <?php echo convertAlertToBootstrap($message_type); ?>"><?php echo $message; ?></div>
<?php endif; ?>

<div class="light">

    <h1><?php echo Language::GetText('change_password_header'); ?></h1>

    <p><?php echo Language::GetText('change_password_text'); ?></p>
    <form action="<?php echo BASE_URL; ?>/account/change-password/" method="post">

        <div class="form-group <?php echo (isset($errors['password']) || isset($errors['match'])) ? 'has-error' : ''; ?>">
            <label class="control-label"><?php echo Language::GetText('new_password'); ?>:</label>
            <input class="form-control" type="password" name="password" />
        </div>
        <div class="form-group <?php echo (isset($errors['confirm_password']) || isset($errors['match'])) ? 'has-error' : ''; ?>">
            <label class="control-label"><?php echo Language::GetText('confirm_password'); ?>:</label>
            <input class="form-control" type="password" name="confirm_password" />
        </div>

        <input type="hidden" name="submitted" value="TRUE" />
        <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
        <input class="btn btn-primary btn-block-mobile" type="submit" name="button" value="<?php echo Language::GetText('change_password_button'); ?>" />
    </form>
</div>