<?php $this->SetLayout ('account'); ?>

<?php if ($message): ?>
    <div class="alert <?=convertAlertToBootstrap($message_type)?>"><?=$message?></div>
<?php endif; ?>

<div class="light">

    <h1><?=Language::GetText('privacy_settings_header')?></h1>

    <form action="<?=HOST?>/account/privacy-settings/" method="post">

        <div class="form-group">
            <label><?=Language::GetText('alert_comment_reply')?>:</label>
            <select class="form-control" name="commentReply">
                <option value="1"<?=($privacy->commentReply) ? ' selected="selected"' : ''?>><?=Language::GetText('yes')?></option>
                <option value="0"<?=(!$privacy->commentReply) ? ' selected="selected"' : ''?>><?=Language::GetText('no')?></option>
            </select>
        </div>

        <input type="hidden" name="video_ready" value="<?php echo (int) $privacy->videoReady; ?>" />
        <input type="hidden" name="video_comment" value="<?php echo (int) $privacy->videoComment; ?>" />
        <input type="hidden" name="new_video" value="<?php echo (int) $privacy->newVideo; ?>" />
        <input type="hidden" name="new_message" value="<?php echo (int) $privacy->newMessage; ?>" />
        <input type="hidden" name="submitted" value="TRUE" />
        <input type="hidden" name="nonce" value="<?php echo $formNonce; ?>" />
        <input class="btn btn-primary btn-block-mobile" type="submit" name="button" value="<?=Language::GetText('privacy_settings_button')?>" />
    </form>
</div>